# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chord.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'chord.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\",\n\x04Node\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xc8\x01\n\x0c\x43hordService\x12\x1d\n\rFindSuccessor\x12\x05.Node\x1a\x05.Node\x12\x17\n\x06Notify\x12\x05.Node\x1a\x06.Empty\x12(\n\tStoreFile\x12\x0c.FileRequest\x1a\r.FileResponse\x12)\n\nLookupFile\x12\x0c.FileRequest\x1a\r.FileResponse\x12+\n\x0cTransferFile\x12\x0c.FileRequest\x1a\r.FileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODE']._serialized_start=15
  _globals['_NODE']._serialized_end=59
  _globals['_FILEREQUEST']._serialized_start=61
  _globals['_FILEREQUEST']._serialized_end=92
  _globals['_FILERESPONSE']._serialized_start=94
  _globals['_FILERESPONSE']._serialized_end=125
  _globals['_EMPTY']._serialized_start=127
  _globals['_EMPTY']._serialized_end=134
  _globals['_CHORDSERVICE']._serialized_start=137
  _globals['_CHORDSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
